export const INSERT_ITEM = 'INSERT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ALL = 'DELETE_ALL';

export const INCREASE_ITEM = 'INCREASE_ITEM';
export const DECREASE_ITEM = 'DECREASE_ITEM';
export const COUNT_CHANGE = 'COUNT_CHANGE';
export const TAKE_ITEMS_FROM_STORAGE = 'TAKE_ITEMS_FROM_STORAGE';
export const UNVAN_ID_ADD = 'UNVAN_ID_ADD';


 

export const INSERT_ITEM_API = 'INSERT_ITEM_API';
export const DELETE_ITEM_API = 'DELETE_ITEM_API';
export const DELETE_ALL_API = 'DELETE_ALL_API';
export const INCREASE_ITEM_API = 'INCREASE_ITEM_API';
export const DECREASE_ITEM_API = 'DECREASE_ITEM_API';
export const COUNT_CHANGE_API = 'COUNT_CHANGE_API';
export const TAKE_ITEMS_FROM_API = 'TAKE_ITEMS_FROM_API';

 
export const LOGIN = 'LOGIN';
export const UNLOG = 'UNLOG';
export const LOGIN_BY_STORAGE = 'LOGIN_BY_STORAGE';

export const ADD_WISHLIST_TO_STORAGE = 'ADD_WISHLIST_TO_STORAGE';
export const DELETE_WISHLIST_FROM_STORAGE = 'DELETE_WISHLIST_FROM_STORAGE';
export const TAKE_WISHLIST_FROM_STORAGE = 'TAKE_WISHLIST_FROM_STORAGE';

export const ADD_WISHLIST_TO_API = 'ADD_WISHLIST_TO_API';
export const DELETE_WISHLIST_FROM_API = 'DELETE_WISHLIST_FROM_API';
export const TAKE_WISHLIST_FROM_API = 'TAKE_WISHLIST_FROM_STORAGE';
 
export const GET_CATEGORIES = 'GET_CATEGORIES' 



export const CREDIT = 'credit';
export const INCASH = 'INCASH';

